Harijung Shahi
(L4CG24)

PROBLEM-1

In [ ]:
import numpy as np
empty_arr = np.zeros((2,2))
print(empty_arr)

[[0. 0.]
 [0. 0.]]


In [ ]:
empty_Arr2=np.zeros((4,2))
print(empty_Arr2)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [ ]:
array_full=np.full(2,2)
print(array_full)

[2 2]


In [ ]:
zeros_arr= np.zeros([2,2])
print(zeros_arr)

[[0. 0.]
 [0. 0.]]


In [ ]:
ones_Arr=np.ones([2,2])
print(ones_Arr)

[[1. 1.]
 [1. 1.]]


In [ ]:
new_list=[1,2,3,4]
array = np.array(new_list)
print(array)

[1 2 3 4]


PROBLEM-2

In [ ]:
array_2 = np.arange(10,50)
print(array_2)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
array_3 = np.array([0,1,2,3,4,5,6,7,8])
new = array_3.reshape(3,3)
print(new)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
identity = np.eye(3,3)
print(identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
random_array = np.random.random(30)
mean_value = random_array.mean()
print("Random array:", random_array)
print("Mean of the array:", mean_value)

Random array: [0.52632095 0.3579112  0.15511046 0.3229689  0.63271665 0.61458133
 0.1313246  0.45320204 0.90389533 0.15537747 0.76409816 0.45896957
 0.90640629 0.29917061 0.2629141  0.65851073 0.6001824  0.85613915
 0.05390938 0.30847935 0.63024667 0.69692321 0.91780825 0.86649497
 0.39853076 0.60263721 0.4832568  0.83471543 0.26062271 0.78661171]
Mean of the array: 0.5300012127941802


In [ ]:
import numpy as np
random_array = np.random.random((10, 10))
min_value = np.min(random_array)
max_value = np.max(random_array)
print("Random Array:")
print(random_array)
print("\nMinimum Value:", min_value)
print("Maximum Value:", max_value)


Random Array:
[[0.46417699 0.12628881 0.40496626 0.04601525 0.9117148  0.51123413
  0.33966658 0.71077803 0.84495727 0.69854344]
 [0.18391062 0.95264365 0.24974514 0.54054405 0.20299582 0.68522134
  0.56892155 0.04319465 0.25646833 0.09982698]
 [0.88990342 0.51912734 0.1132613  0.70224169 0.06371461 0.82371738
  0.88282646 0.31751539 0.95315873 0.85466142]
 [0.8748259  0.81998499 0.30191746 0.6306193  0.30901968 0.68352816
  0.02646675 0.21596674 0.11752895 0.39726146]
 [0.34206788 0.35329055 0.61185691 0.2083732  0.29132899 0.18835648
  0.87291423 0.23319275 0.27295923 0.67845667]
 [0.34350572 0.46333902 0.24216449 0.75360737 0.11386009 0.11914768
  0.26868849 0.11454916 0.97341516 0.97056868]
 [0.95088452 0.28392503 0.71720533 0.21715362 0.37327041 0.68060381
  0.26559513 0.54384251 0.61285631 0.12686433]
 [0.38632925 0.07506711 0.52399945 0.20514623 0.03360605 0.6038719
  0.76977294 0.39015154 0.11516144 0.07709992]
 [0.37292229 0.37448606 0.86689456 0.58915378 0.02315237 0.64331114

In [ ]:
zero_array = np.zeros(10)
zero_array[4] = 1
print(zero_array)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [ ]:
arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]
print(reversed_arr)

[0 4 0 0 2 1]


In [ ]:
array_6 = np.array([[1,0,0,0]])
print(array_6)

[[1 0 0 0]]


PROBLEM-3

In [ ]:
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

# Task-1
add = x + y
add2 = w + v
print("Addition1:\n", add)
print("Addition2:\n", add2)

#Task-2

sub = x-y
sub2= w-v
print("Subtraction1:\n", sub)
print("Subtraction2:\n", sub2)


#Task-3
new_x = x*2
new_y = y*3
new_v = v*4
new_w = w*5
print("X:\n", new_x)
print("Y:\n", new_y)
print("V:\n", new_v)
print("Z:\n", new_w)

#Task-4
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])
sqrt_x = np.sqrt(x)
sqrt_y = np.sqrt(y)
sqrt_v = np.sqrt(v)
sqrt_w = np.sqrt(w)

print("Square root of x:\n", sqrt_x)
print("Square root of y:\n", sqrt_y)
print("Square root of v:\n", sqrt_v)
print("Square root of w:\n", sqrt_w)

#Task-5
dot_v_w=np.dot(v,w)
dot_x_v=np.dot(x,v)
dot_x_y=np.dot(x,y)
print("Dot product of v and w arrays:\n", dot_v_w)
print("Dot product of x and v arrays:\n", dot_x_v)
print("Dot product of x and y arrays:\n", dot_x_y)

#Task-6

array_v_w = np.stack((v, w), axis=0)
print("Stacked v and w arrays:\n", array_v_w)


array_x_y = np.vstack((x, y))
print("Stacked x and y arrays (vertically):\n", array_x_y)

Addition1:
 [[ 6  8]
 [10 13]]
Addition2:
 [20 22]
Subtraction1:
 [[-4 -4]
 [-4 -3]]
Subtraction2:
 [2 2]
X:
 [[ 2  4]
 [ 6 10]]
Y:
 [[15 18]
 [21 24]]
V:
 [36 40]
Z:
 [55 60]
Square root of x:
 [[1.         1.41421356]
 [1.73205081 2.23606798]]
Square root of y:
 [[2.23606798 2.44948974]
 [2.64575131 2.82842712]]
Square root of v:
 [3.         3.16227766]
Square root of w:
 [3.31662479 3.46410162]
Dot product of v and w arrays:
 219
Dot product of x and v arrays:
 [29 77]
Dot product of x and y arrays:
 [[19 22]
 [50 58]]
Stacked v and w arrays:
 [[ 9 10]
 [11 12]]
Stacked x and y arrays (vertically):
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]


PROBLEM-4

In [ ]:
A = np.array([[3, 4], [7, 8]])


A_inv = np.linalg.inv(A)


result = np.dot(A, A_inv)

print("A * A_inv = \n", result)


I = np.eye(2)

print("\nIdentity matrix I:\n", I)
print("\nIs A * A_inv approximately equal to I? ", np.allclose(result, I))


#task-2
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

# Compute the product AB
AB = np.dot(A, B)

# Compute the product BA
BA = np.dot(B, A)

# Print the results
print("AB = \n", AB)
print("\nBA = \n", BA)

# Verify if AB is equal to BA
print("\nIs AB equal to BA? ", np.array_equal(AB, BA))

A * A_inv = 
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]

Identity matrix I:
 [[1. 0.]
 [0. 1.]]

Is A * A_inv approximately equal to I?  True
AB = 
 [[23 13]
 [51 29]]

BA = 
 [[36 44]
 [13 16]]

Is AB equal to BA?  False
